using DotNetBasico.ArrayExemplos;
using DotNetBasico.Metodos;
using DotNetBasico.Modificadores;
using DotNetBasico.POO;
using DotNetBasico.Tomadas;

//Exemplo01.Main(args);
//Exemplo02.Main(args);
//Exemplo_if.Main(args);
//Exemplo10.Main(args);
//Exemplo11.Main(args);
//Exemplo12.Main(args);
//Exemplo13.Main(args);
//Exemplo14.Main(args);
//Exemplo01Array.Main(args);
//Exemplo02Array.Main(args);
//Exemplo03Array.Main(args);  
//Exemplo04Array.Main(args);
//Exemplo05Array.Main(args);
//Exemplo06ArrayMetodos.Main(args);
//Exemplo01Matriz.Main(args);
//Exemplo02Matriz.Main(args);
//Exemplo03Matriz.Main(args);
//Exemplo01Metodo.Main(args);
//Exemplo02Metodos.Main(args);
//Exemplo03Metodos.Main(args);
//Exemplo04Metodo.Main(args);
//Exemplo05Metodos.Main(args);
//Exemplo06Metodos.Main(args);
//Exemplo07Metodos.Main(args);
//Exemplo08Metodo.Main(args);
//ExemploCarro.Main(args);
//Cadastramento.Main(args);
//ExibirVendas.Main(args);
//Veiculo.Main(args);
//ConstrutorExibirBala.Main(args);
//Moto.Main(args);
Privado.Main(args);